create table if not exists categories
(
    id      integer generated by default as identity
        constraint category_id_pk
            primary key,
    user_id integer not null
        constraint user_id_fk
            references users
            on delete restrict,
    name    varchar not null
);
