create table if not exists chores
(
    id          integer generated by default as identity
        constraint chores_pk
            primary key,
    category_id integer
        constraint chores_category_fk
            references categories,
    name        varchar not null
);