create table if not exists users
(
    id         integer generated by default as identity
    constraint id_pk
    primary key,
    first_name varchar not null,
    last_name  varchar not null,
    email      varchar not null
    constraint email_unique
    unique
);